import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import { useContext } from "react";
import { ShowcaseContext } from "../context/showcaseContext";

import Header from "./Header";
import SectionFour from "./SectionFour";
import { Container, Text, Title, Grid } from "@mantine/core";

export default function Home() {
  const { projects } = useContext(ShowcaseContext);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <main className={styles.main}>
        <section>
          <Container size="xl">
            <Grid>
              {projects &&
                projects.map((project: any) => (
                  <SectionFour key={project.id} project={project.data} />
                ))}
            </Grid>
          </Container>
        </section>
      </main>
      <footer className={styles.footer}>
        Fear has killed more dreams than failure
      </footer>
    </div>
  );
}
