import Head from "next/head";
import styles from "../styles/Home.module.css";

import { useContext } from "react";
import { ShowcaseContext } from "../context/showcaseContext";

import Header from "./Header";
import ProjectCard from "./projectCard";
import { Container, Grid } from "@mantine/core";

export default function Home() {
  const { projects } = useContext(ShowcaseContext);

  return (
    <div className={styles.container}>
      <Head>
        <title>Showcase</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <main className={styles.main}>
        <section>
          <Container size="xl">
            <Grid>
              {projects &&
                projects.map((project: any, index: number) => (
                  <Grid.Col key={index} xs={12} sm={6} md={4} lg={3}>
                    <ProjectCard key={project?.key} project={project?.data} />
                  </Grid.Col>
                ))}
            </Grid>
          </Container>
        </section>
      </main>
      <footer className={styles.footer}>
        Fear has killed more dreams than failure
      </footer>
    </div>
  );
}
