import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { ActionIcon, useMantineColorScheme } from "@mantine/core";
import { IconSun, IconMoonStars } from "@tabler/icons";
import { useContext } from "react";
import { ShowcaseContext } from "../context/showcaseContext";

export default function Home() {
  const { projects } = useContext(ShowcaseContext);

  const { colorScheme, toggleColorScheme } = useMantineColorScheme();
  const dark = colorScheme === "dark";
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ActionIcon
          variant="outline"
          color={dark ? "yellow" : "blue"}
          onClick={() => toggleColorScheme()}
          title="Toggle color scheme"
        >
          {dark ? <IconSun size={18} /> : <IconMoonStars size={18} />}
        </ActionIcon>
        <h1 className={styles.title}>
          My <a href="#">Projects!</a>
        </h1>

        <div className={styles.grid}>
          {projects &&
            projects.map((project) => (
              <a
                href={project.data.github}
                target="blank"
                className={styles.card}
              >
                <h2>{project.data.name} &rarr;</h2>
                <p>{project.data.description}</p>
              </a>
            ))}
        </div>
      </main>

      <footer className={styles.footer}>
        Fear has killed more dreams than failure
      </footer>
    </div>
  );
}
